- name: Build Docker Image
  hosts: web
  become: yes
  tasks:
    - name: Build Docker Image
      command: docker build -t my-nextjs-app:latest -f Dockerfile .
      args:
        chdir: ~/66026000-nextjs 
